using UnityEngine;

public class BallObject : MonoBehaviour
{

    private void Start()
    {
        EventManager.LevelRestart += RespawnBall;    
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        // CASE 1: Ball is hit by a projectile generated by another ball object.
        if (other.gameObject.GetComponent<WhiteBallObject>() != null)
        {
            ManageProjectileCollision(other);
        }
        // CASE 2: Ball is hit by player cursor.
        else if (other.gameObject.GetComponent<CursorController>() != null)
        {
            ManageCursorCollision(other);
        }
        // CASE 3: Not a valid object type.
        else return;

        // In all cases where collision occurs against a valid object:
        AfterCollision();

    }

    // determines how the ball object should behave when hit by a projectile.
    private void ManageProjectileCollision(Collider2D other)
    {
        GetComponent<Animator>().SetTrigger("Fade");
        Destroy(other.gameObject);
    }

    // determines how the ball object should behave when hit by player cursor.
    private void ManageCursorCollision(Collider2D other)
    {
        GetComponent<Animator>().SetTrigger("Fade");
    }

    // determines what to do after all specific cases have been handled.
    protected virtual void AfterCollision()
    {
        // disable collider so that gameobjects can no longer interact with ball
        GetComponent<Collider2D>().enabled = false;

        // and send signal to notify that ball was collided with.
        EventManager.CallBallTouched(this);
    }


    protected virtual void RespawnBall()
    {
        // resets all triggers to prevent animation mishaps.
        GetComponent<Animator>().ResetTrigger("Shrink");
        GetComponent<Animator>().ResetTrigger("Fade");

        // if collider is enabled, ball hasn't been collided with yet, and so we don't need to spawn it again.
        if (GetComponent<Collider2D>().enabled) return;

        // enable collider and play instantiation clip.
        GetComponent<Collider2D>().enabled = true;
        GetComponent<Animator>().SetTrigger("Instantiate");
    }

    private void OnDisable()
    {
        EventManager.LevelRestart -= RespawnBall;
    }
}
